import { faker } from "@faker-js/faker";

export default function handler(req, res) {
    res.status(200).json(createClass());
}

const courseMap = {
    AAE: "Aeronautical and Astronautical Engineering",
    ACTG: "Accounting",
    AEC: "Applied Economics",
    AED: "Agricultural Education",
    AGRI: "Agricultural Science",
    AHE: "Adult and Higher Education Leadershp",
    AI: "Artificial Intelligence",
    AJ: "Applied Journalism",
    ALS: "Academic Learning Services",
    AMS: "American Studies",
    ANS: "Animal Sciences",
    ANTH: "Anthropology",
    ARAB: "Arabic",
    ARE: "Architectural Engineering",
    ART: "Art",
    AS: "Aerospace Studies",
    ASL: "American Sign Language",
    ASN: "Asian Languages and Cultures",
    ATS: "Atmospheric Sciences",
    BA: "Business Administration",
    BB: "Biochemistry and Biophysics",
    BDS: "Biological Data Sciences",
    BEE: "Biological and Ecological Engineering",
    BHS: "Bio-Health Sciences",
    BI: "Biology",
    BIOE: "Biological Engineering",
    BOT: "Botany and Plant Pathology",
    BRR: "Bioresource Research",
    CBEE: "Chemistry, Biology, and Environmental Engineering",
    CCE: "Civil and Construction Engineering",
    CE: "Civil Engineering",
    CEM: "Construction Engineering Management",
    CH: "Chemistry",
    CHE: "Chemical Engineering",
    CHN: "Chinese",
    COMM: "Communication",
    COUN: "Counseling",
    CROP: "Crop Science",
    CS: "Computer Science",
    CSS: "Crop and Soil Science",
    CSSA: "College Student Services Admin",
    DHE: "Design and Human Environment",
    DSGN: "Design",
    EAH: "Environmental Arts and Humanities",
    ECE: "Electrical and Computer Engineering",
    ECON: "Economics",
    ED: "Education",
    EMGT: "Engineering Management",
    ENG: "English",
    ENGR: "Engineering Science",
    ENSC: "Environmental Sciences",
    ENT: "Entomology",
    ENVE: "Environmental Engineering",
    ES: "Ethnic Studies",
    ESC: "Science of Engineering",
    ESE: "Energy Systems Engineering",
    FE: "Forest Engineering",
    FES: "Forest Ecosystems and Society",
    FILM: "Film Studies",
    FIN: "Finance",
    FOR: "Forestry",
    FR: "French",
    FST: "Food Science and Technology",
    FW: "Fisheries and Wildlife",
    GD: "Graphic Design",
    GEO: "Geosciences",
    GEOG: "Geography",
    GER: "German",
    GPH: "Geophysics",
    GRAD: "Graduate Education",
    GS: "General Science",
    H: "Public Health",
    HC: "Honors College",
    HDFS: "Human Development and Family Sciences",
    HEBR: "Hebrew",
    HEST: "Humanitarian Engineering Science and Technology",
    HHS: "Health and Human Sciences",
    HM: "Hospitality Management",
    HORT: "Horticulture",
    HST: "History",
    IAWS: "Integrated Agriculture and Wildland Science ",
    IB: "Integrative Biology",
    IE: "Industrial and Manufacturing Engineering",
    IT: "Italian",
    JPN: "Japanese",
    KIN: "Kinesiology",
    KOR: "Korean",
    LA: "Liberal Arts",
    LAT: "Latin",
    LEAD: "Leadership",
    LIB: "Library and Information Science",
    LING: "Linguistics",
    LS: "Liberal Studies",
    MAST: "Marine Studies",
    MATS: "Materials Science",
    MB: "Microbiology",
    MCB: "Molecular and Cellular Biology",
    ME: "Mechanical Engineering",
    MFGE: "Manufacturing Engineering",
    MRKT: "Marketing",
    MRM: "Marine Resource Management",
    MS: "Military Science",
    MTH: "Mathematics",
    MUED: "Music Education",
    MUS: "Music",
    NMC: "New Media Communications",
    NR: "Natural Resources",
    NS: "Naval Science",
    NSE: "Nuclear Science and Engineering",
    NUR: "Nursing",
    NUTR: "Nutrition",
    OC: "Oceanography",
    OEAS: "Ocean Earth and Atmospheric Sciences",
    PAC: "Physical Activity Courses",
    PAX: "Peace Studies",
    PBG: "Plant Breeding and Genetics",
    PH: "Physics",
    PHAR: "Pharmacy",
    PHL: "Philosophy",
    PPOL: "Public Policy",
    PS: "Political Science",
    PSY: "Psychology",
    PT: "Physical Therapy",
    QS: "Queer Studies",
    REL: "Religious Studies",
    RNG: "Rangeland Ecology and Management",
    ROB: "Robotics",
    RS: "Rural Studies",
    RUS: "Russian",
    SCI: "Science",
    SE: "Software Engineering",
    SED: "Science and Mathematics Education",
    SNR: "Sustainable Natural Resources",
    SOC: "Sociology",
    SOIL: "Soil Science",
    SPAN: "Spanish",
    SSCI: "Social Science",
    ST: "Statistics",
    SUS: "Sustainability",
    TA: "Theatre Arts",
    TOX: "Toxicology",
    TRAL: "Tourism, Recreation, and Adventure Leadership",
    VM: "Veterinary Medicine",
    WGSS: "Women, Gender, and Sexuality",
    WLC: "World Languages and Cultures",
    WR: "Written English",
    WRE: "Water Resources Engineering",
    WRP: "Water Resources Policy and Management",
    WRS: "Water Resources Science",
    WSE: "Wood Science and Engineering",
    Z: "Zoology",
};

const quarters = ["Fall", "Winter", "Spring", "Summer"];
const years = ["2022", "2023"];

function getRandomValueFromArray(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomKeyFromObject(obj) {
    return Object.keys(obj)[
        Math.floor(Math.random() * Object.keys(courseMap).length)
    ];
}

function getCourseNumber() {
    return Math.floor(Math.random() * 399) + 100;
}

export function createClass() {
    const instructor = `${faker.name.firstName()} ${faker.name.lastName()}`;
    const departmentInitials = getRandomKeyFromObject(courseMap);
    const department = courseMap[departmentInitials];
    const classInitialism = `${departmentInitials} ${getCourseNumber()}`;
    const quarter = getRandomValueFromArray(quarters);
    const year = getRandomValueFromArray(years);

    return {
        classTitle: classInitialism,
        department: department,
        quarter: `${quarter} ${year}`,
        instructor: instructor,
    };
}
